import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/layout/header";

export const metadata: Metadata = {
	title: "NEGITORO LIFE",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased bg-gray-100 dark:bg-gray-900">
				<Header />
				{children}
			</body>
		</html>
	);
}
